"""Initial migration.

Revision ID: 10f7e37a14b2
Revises: 1e6a6f50ac70
Create Date: 2023-03-23 17:31:05.154290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f7e37a14b2'
down_revision = '1e6a6f50ac70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('tag_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint('tag_name_key', ['name'])

    # ### end Alembic commands ###
