"""Initial migration.

Revision ID: c75a13b16c1b
Revises: 10f7e37a14b2
Create Date: 2023-03-23 17:37:56.237107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75a13b16c1b'
down_revision = '10f7e37a14b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_assignment_content_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_unique_constraint('post_assignment_content_key', ['assignment_content'])

    # ### end Alembic commands ###
